### ISSUE TITLE
Utilização CorreiosHX

### ISSUE THREAD

**Issue by iamelisandromello** [HXPHP/hxphp-correios#1]
Não consegui entender como executa a chamada do módulo.  Carreguei o serviço no controller:
$this->load(
    'Services\Correios',
    $this->request->get('cep') // 00000-000
);
Mas, em qual momento informo o CEP a ser pesquisado?

Quais parâmetros devo informar  no método getDados()?
$retornoJSON = $this->correios->getDados();

Poderia postar um exemplo?

**Comment by brunosantoshx** [comment]
Olá @iamelisandromello, boa noite. Tudo bem?

Neste exemplo o CEP é passado em uma variável GET nomeada de `cep`, ou seja, o valor está sendo passado diretamente na `URI`: http://localhost/hxphp/correios/buscar/?cep=00000-000.

Você é quem define como, quando e onde o CEP será inserido e processado, isto é, ali poderia ser um `$this->request->post('cep')` que recebe o CEP de um formulário.

Já sobre o método `getDados()`, ele não recebe parâmetros, afinal, todas as informações já foram passadas diretamente no construtor.

Espero ter te ajudado.
Forte abraço e sucesso sempre!

**Comment by iamelisandromello** [comment]
Obrigado Bruno Resolveu sim;
Estou utilizando o framework HXPHP como base para meu TCC no curso de Ciência da Computação, para o desenvolvimento de um Sistema WEB de Análise de Perfil Profissional de profissionais de TI,  com metodologia RBC (Raciocínio Baseado em Casos) como solução de Inteligência Artificial. Seus materiais tem me auxiliado demais.

Forte Abraço. Deus Abençoe.

**Comment by brunosantoshx** [comment]
Olá @iamelisandromello, tudo bem?

Caraca! Que massa! Você pode me passar mais detalhes? Meu e-mail é contato@hxphp.com.br. Pretendo adicionar os cases feitos com o HXPHP no site oficial em breve. 

Sucesso no TCC!
Forte abraço e sucesso sempre!
